language: go
go_import_path: gocloud.dev
go: "1.11.x"

before_install:
  - "df -k"
  # The Bash that comes with OS X is ancient.
  # grep is similar: it's not GNU grep, which means commands aren't portable.
  # Homebrew installs grep as ggrep if you don't build from source, so it needs
  # moving so it takes precedence in the PATH.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      HOMEBREW_NO_AUTO_UPDATE=1 brew install bash grep;
      mv $(brew --prefix)/bin/ggrep $(brew --prefix)/bin/grep;
    fi

install:
  # Re-checkout files preserving line feeds. This prevents Windows builds from
  # converting \n to \r\n.
  - "git config --global core.autocrlf input"
  - "git checkout -- ."
  - "go install github.com/google/wire/cmd/wire"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      go install github.com/mattn/goveralls;
    fi

script:
  - 'internal/testing/runchecks.sh'

env:
  global:
  - GO111MODULE=on

jobs:
  include:
    - os: linux
    - os: osx
    # TODO(#1075): Uncomment the lines below to re-enable the Windows build on
    # master once it passes; currently it always fails due to a Travis bug
    # regarding secrets.
    # # Only run Windows build job on master; it's very slow.
    # - os: windows
    #   if: branch = master AND type = push
    # Deploy to GitHub Pages.
    - stage: website
      os: linux
      install: "curl -fsSL https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.tar.gz | tar zxf - -C \"$HOME\" hugo"
      script: "HUGO_GOOGLEANALYTICS=UA-135118641-1 \"$HOME/hugo\" -s internal/website"
      deploy:
        provider: pages
        fqdn: gocloud.dev
        skip-cleanup: true
        local-dir: internal/website/public
        github-token: $GITHUB_TOKEN  # set in the Settings page of the repo
        keep-history: true
        verbose: true  # temporarily, while verifying
        on:
          branch: master

stages:
  - test
  - name: website
    if: branch = master AND type = push
