os:
  - windows

language: go
go_import_path: github.com/google/go-cloud
go: "1.11.x"

before_install:
  - "df -k"
  - "git config --global core.autocrlf input"
  # The Bash that comes with OS X is ancient.
  # checkpr.sh needs Bash 4. It's OK to not worry about this issue for
  # customers as checkpr.sh is only for running on Travis.
  # grep is similar: it's not GNU grep, which means commands aren't portable.
  # Homebrew installs grep as ggrep if you don't build from source, so it needs
  # moving so it takes precedence in the PATH.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      HOMEBREW_NO_AUTO_UPDATE=1 brew install bash grep;
      mv $(brew --prefix)/bin/ggrep $(brew --prefix)/bin/grep;
    fi

install:
  - "git clone --depth=50 https://github.com/google/go-cloud.git google/go-cloud"
  - "go install ./wire/cmd/wire"

script:
  # TRAVIS_PULL_REQUEST is set to "false" for branch builds, and the PR number
  # for pull request builds. Branch builds should test everything.
  - 'if [[ "$TRAVIS_PULL_REQUEST" != false ]]; then internal/testing/checkpr.sh -short -race; else go test -short -race ./...; fi'
  - '[[ "$TRAVIS_PULL_REQUEST" != false ]] || internal/testing/wirecheck.sh'

env:
  global:
  - GOPROXY=https://storage.googleapis.com/go-cloud-modules/
  - GO111MODULE=on
