language: go
go_import_path: gocloud.dev
go: "1.11.x"

before_install:
  - "df -k"
  # The Bash that comes with OS X is ancient.
  # grep is similar: it's not GNU grep, which means commands aren't portable.
  # Homebrew installs grep as ggrep if you don't build from source, so it needs
  # moving so it takes precedence in the PATH.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      HOMEBREW_NO_AUTO_UPDATE=1 brew install bash grep;
      mv $(brew --prefix)/bin/ggrep $(brew --prefix)/bin/grep;
    fi

install:
  # Re-checkout files preserving line feeds. This prevents Windows builds from
  # converting \n to \r\n.
  - "git config --global core.autocrlf input"
  - "git checkout -- ."
  - "go install github.com/google/wire/cmd/wire"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      go install github.com/mattn/goveralls;
    fi

script:
  - 'internal/testing/runchecks.sh'

env:
  global:
  - GOPROXY=https://storage.googleapis.com/go-cloud-modules/
  - GO111MODULE=on

jobs:
  include:
    - os: linux
    - os: osx
    # Only run Windows build job on master. This would be listed in `os:` above,
    # but matrix expansion does not allow conditionals. See:
    # https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#conditional-jobs
    - os: windows
      if: branch = master #AND type = push
    # Generate imports for GitHub Pages.
    - stage: imports
      os: linux
      script: ./internal/imports/makeimports.sh
      deploy:
        provider: pages
        fqdn: gocloud.dev
        skip-cleanup: true
        local-dir: makeimports-output
        github-token: $GITHUB_TOKEN  # set in the Settings page of the repo
        keep-history: true
        verbose: true  # temporarily, while verifying
        on:
          branch: master

stages:
  - test
  - name: imports
    if: branch = master AND type = push
